---
- hosts: all
  become: true
  tasks:
   - name: Copy
     copy:
       src: /home/vagrant/spring-petclinic/target/spring-petclinic-2.7.3.jar
       dest: /home/ubuntu/
   - name: Deploy
     shell: nohup java -jar /home/ubuntu/spring-petclinic-2.7.3.jar & 1>&2 > /dev/null
